Add 贡献方式
opensourceai/news pull request #1
Opened 2019-11-19 05:00 UTC by chenquan

2019-11-20 06:54 UTC, ZhuoYaZhao commented
OK

2019-11-20 07:02 UTC, ZhuoYaZhao submitted a review, later dismissed

2019-11-21 02:21 UTC, heqiang requested changes
### 前言技术

2019-11-21 02:22 UTC, chenquan commented
> ### 前言技术

这段已经更改了的

2019-11-21 02:23 UTC, heqiang reviewed
ok

2019-11-21 02:42 UTC, heqiang submitted a review, later dismissed

2019-11-22 03:42 UTC, ZhuoYaZhao approved these changes

2019-11-22 03:45 UTC, merged